import type { AiCatalogItem } from "./types";

export const AI_CATALOG: AiCatalogItem[] = [
  {
    name: "ChatGPT",
    company: "OpenAI",
    mark: "@chatgpt",
    desc: "The household name. Best first AI to learn — strong on everyday writing, brainstorming, light coding, and conversational research.",
    bestAt: "General use",
    category: "Chat",
    modalities: ["Chat", "Voice", "Vision", "Image"],
    skill: "Beginner",
    pricing: "Freemium",
    featured: true,
    lessons: 42,
  },
  {
    name: "Claude",
    company: "Anthropic",
    mark: "@claude",
    desc: "The writer's AI. Best for long-document reasoning, careful editing, code refactors, and anything that needs nuance over speed.",
    bestAt: "Writing & reasoning",
    category: "Chat",
    modalities: ["Chat", "Vision", "Code"],
    skill: "Beginner",
    pricing: "Freemium",
    lessons: 38,
  },
  {
    name: "Gemini",
    company: "Google",
    mark: "@gemini",
    desc: "The Google ecosystem AI. Lives inside Workspace; best when your work already flows through Docs, Sheets, Gmail, and Meet.",
    bestAt: "Workspace integration",
    category: "Chat",
    modalities: ["Chat", "Voice", "Vision", "Image"],
    skill: "Beginner",
    pricing: "Freemium",
    lessons: 28,
  },
  {
    name: "Copilot",
    company: "Microsoft",
    mark: "@copilot",
    desc: "Microsoft's AI built into Windows, Office, and Edge. Best if you live in Outlook, Excel, or Teams every day.",
    bestAt: "Microsoft 365",
    category: "Chat",
    modalities: ["Chat", "Voice", "Vision"],
    skill: "Beginner",
    pricing: "Paid",
    lessons: 18,
  },
  {
    name: "Cursor",
    company: "Anysphere",
    mark: "@cursor",
    desc: "The AI-native code editor. Forked VS Code with Claude / GPT baked in. The IDE professional developers are switching to.",
    bestAt: "Coding",
    category: "Code",
    modalities: ["Code", "Chat"],
    skill: "Intermediate",
    pricing: "Freemium",
    lessons: 24,
  },
  {
    name: "Midjourney",
    company: "Midjourney",
    mark: "@midjourney",
    desc: "The image AI that defined the aesthetic. Best for polished, painterly, art-directed visuals. Lives inside Discord.",
    bestAt: "Image generation",
    category: "Image",
    modalities: ["Image"],
    skill: "Intermediate",
    pricing: "Paid",
    lessons: 20,
  },
  {
    name: "Perplexity",
    company: "Perplexity",
    mark: "@perplexity",
    desc: "AI search engine. Live web results with citations and follow-up questions. Best for research where sources matter.",
    bestAt: "Live web research",
    category: "Search",
    modalities: ["Chat", "Search"],
    skill: "Beginner",
    pricing: "Freemium",
    lessons: 16,
  },
  {
    name: "Llama",
    company: "Meta",
    mark: "@llama",
    desc: "The open-weight foundation model. Run it on your own hardware. Best if you care about privacy, cost, or customization.",
    bestAt: "Self-hosted AI",
    category: "Foundation",
    modalities: ["Chat", "Code", "Vision"],
    skill: "Advanced",
    pricing: "Free",
    lessons: 14,
  },
  {
    name: "DeepSeek",
    company: "DeepSeek",
    mark: "@deepseek",
    desc: "Frontier reasoning at a fraction of the cost. The model that proved you don't need OpenAI-scale spending to compete.",
    bestAt: "Cheap reasoning",
    category: "Foundation",
    modalities: ["Chat", "Code"],
    skill: "Intermediate",
    pricing: "Free",
    lessons: 10,
  },
  {
    name: "Grok",
    company: "xAI",
    mark: "@grok",
    desc: "Elon's AI. Tied tightly to X (Twitter) — strong on real-time social signal and unfiltered tone. Polarizing by design.",
    bestAt: "Real-time + social",
    category: "Chat",
    modalities: ["Chat", "Vision"],
    skill: "Intermediate",
    pricing: "Paid",
    lessons: 12,
  },
];
