// Catalog of all 10 models — drives the universal model lesson page.
// The page reads ?model=<slug> from the URL and renders the matching entry.

const MODELS_CATALOG = {
  chatgpt: {
    name:"ChatGPT", by:"OpenAI", version:"GPT-5 · 2026", mark:"@chatgpt",
    tagline:"The most-used general-purpose AI assistant.",
    compare:[ {name:"Claude"}, {name:"Gemini"}, {name:"Perplexity"} ],
    lessons:[
      { n:"01", title:"What ChatGPT actually is", level:"Basics", dur:"3:42",
        desc:"How a language model works, what 'GPT' means, and why this one became the household name.",
        callout:{ label:"Get the mental model", text:"It's not magic — it's autocomplete with a graduate degree. Watch the 2-min visual." },
        prompt:"Explain how a large language model works like I'm 12 years old.\nUse one analogy and keep it under 200 words.",
        note:"Not magic. It's autocomplete\non steroids — predict next word." },
      { n:"02", title:"Writing your first useful prompt", level:"Basics", dur:"5:18",
        desc:"The prompt formula: role + context + task + format. Try 3 examples live.",
        callout:{ label:"The formula", text:"Role + Context + Task + Format = a prompt that actually returns what you wanted." },
        prompt:"You're a senior copywriter.\nRewrite this headline 5 different ways:\n  \"{headline}\"\nVary the tone — punchy, warm, formal, playful, urgent.",
        note:"Bad prompt = vague answer.\nSpecific prompt = sharp answer." },
      { n:"03", title:"Conversation memory & projects", level:"Basics", dur:"4:30",
        desc:"How to use Projects, Custom Instructions, and Memory so you don't repeat yourself.",
        callout:{ label:"Pause and try this", text:"Open Settings → Personalization → Custom Instructions. Paste your default style guide. Save." },
        prompt:"Set this in Custom Instructions:\n\"I write in a direct, no-jargon style.\nAlways cut filler words and avoid em-dashes.\"",
        note:"Memory off in this lesson?\nToggle in Settings → Memory." },
      { n:"04", title:"Voice mode for thinking out loud", level:"Practical", dur:"6:02",
        desc:"When voice beats typing. Hands-free brainstorming workflow.",
        callout:{ label:"Try it walking", text:"Best 1-2 punch: voice mode + a walk around the block. Non-linear thinking unlocked." },
        prompt:"(Open voice mode)\n\"Help me draft an email to my landlord about\nthe leak in the bathroom — I'll explain by talking.\"",
        note:"Voice ≠ dictation.\nIt's a real conversation." },
      { n:"05", title:"Vision: feed it images & screenshots", level:"Practical", dur:"5:44",
        desc:"Solving math from a photo, reading charts, drafting from a whiteboard.",
        callout:{ label:"Use cases that just work", text:"Receipt → expense report. Whiteboard photo → meeting notes. Chart → plain-English summary." },
        prompt:"(Upload a screenshot of a math problem)\n\"Solve this step by step.\nFor each step, explain why you did it.\"",
        note:"Screenshot tool + vision\n= free, smarter OCR." },
      { n:"06", title:"Code Interpreter for non-coders", level:"Pro", dur:"8:55",
        desc:"Drop in a CSV, ask questions, get charts. Skip Excel forever.",
        callout:{ label:"No code required", text:"Drag in any spreadsheet. Ask in plain English. Get answers + charts back in seconds." },
        prompt:"(Upload your CSV)\n\"Find the top 5 trends in this data.\nChart the most surprising one.\nExplain why it's surprising.\"",
        note:"CSV → answers in 30 sec.\nThis is the killer feature." },
      { n:"07", title:"Custom GPTs you'll actually use", level:"Pro", dur:"9:20",
        desc:"Build a personal writing coach, code reviewer, or travel planner in 15 minutes.",
        callout:{ label:"Pin one to your sidebar", text:"Build a tool once, use it forever. Stop re-prompting from scratch every time." },
        prompt:"Build me a Custom GPT named \"Tone Coach\":\nGive brutally honest feedback on tone,\nbrevity, and clarity. Cite the line. Don't soften.",
        note:"Custom GPTs > plain ChatGPT\nfor any task you repeat." },
    ],
  },

  claude: {
    name:"Claude", by:"Anthropic", version:"Claude 5 · 2026", mark:"@claude",
    tagline:"The writer's and reasoner's AI — careful over fast.",
    compare:[ {name:"ChatGPT"}, {name:"Cursor"}, {name:"Perplexity"} ],
    lessons:[
      { n:"01", title:"Why Claude feels different", level:"Basics", dur:"3:30",
        desc:"Anthropic's focus on careful, steerable reasoning — and what that means for your work.",
        callout:{ label:"The vibe", text:"Claude trades a little speed for nuance, long-context handling, and fewer confident-but-wrong answers." },
        prompt:"Read this 20-page doc and give me:\n1) a 5-bullet summary\n2) the 3 weakest arguments\n3) what's missing.",
        note:"Reach for Claude when the\nstakes are nuance, not speed." },
      { n:"02", title:"Long documents & big context", level:"Basics", dur:"4:48",
        desc:"Paste whole reports, contracts, or codebases and reason across all of it at once.",
        callout:{ label:"Dump it all in", text:"Claude's long context means you rarely need to chunk. Paste the whole thing and ask." },
        prompt:"Here's a 60-page contract.\nList every obligation that falls on ME,\nwith the page number, in a table.",
        note:"Big context = fewer\n\"as I mentioned earlier\" misses." },
      { n:"03", title:"Projects & style that sticks", level:"Basics", dur:"4:10",
        desc:"Set up a Project with your docs and writing style so every chat starts informed.",
        callout:{ label:"Set it once", text:"Add your style guide + reference docs to a Project. Every conversation inherits them." },
        prompt:"(In a Project) Custom instructions:\n\"Match my voice: plain, direct, no hype.\nAlways ask a clarifying question first.\"",
        note:"Projects = a coworker who\nalready read the brief." },
      { n:"04", title:"Refactoring & reviewing code", level:"Practical", dur:"6:40",
        desc:"Where Claude shines for developers: explaining, refactoring, and reviewing diffs.",
        callout:{ label:"Best for review", text:"Paste a diff and ask for a review. Claude catches edge cases and explains its reasoning." },
        prompt:"Review this pull request.\nFlag bugs, edge cases, and naming issues.\nQuote the exact line for each note.",
        note:"Plan & review with Claude,\nimplement in Cursor." },
      { n:"05", title:"Artifacts: build as you chat", level:"Practical", dur:"5:30",
        desc:"Generate documents, apps, and diagrams in a side panel you can iterate on live.",
        callout:{ label:"Watch it build", text:"Ask for a tool or doc and Claude renders it in an Artifact you can refine turn by turn." },
        prompt:"Build a single-page habit tracker as an artifact.\nViolet theme, 7-day grid, works offline.",
        note:"Artifacts = see the output,\nnot just describe it." },
      { n:"06", title:"Honest limits & when to switch", level:"Pro", dur:"5:05",
        desc:"Where Claude is weaker — real-time info, image generation — and what to pair it with.",
        callout:{ label:"Know the edges", text:"No live web by default and no image generation. Pair with Perplexity and Midjourney." },
        prompt:"What don't you know about events\nafter your training cutoff?\nList what I should verify elsewhere.",
        note:"Pair Claude (reason) with\nPerplexity (facts)." },
    ],
  },

  gemini: {
    name:"Gemini", by:"Google", version:"Gemini Ultra · 2026", mark:"@gemini",
    tagline:"Google's AI, woven through Workspace.",
    compare:[ {name:"ChatGPT"}, {name:"Copilot"}, {name:"Perplexity"} ],
    lessons:[
      { n:"01", title:"Gemini in the Google world", level:"Basics", dur:"3:20",
        desc:"Why Gemini's superpower is living inside Docs, Sheets, Gmail, and Meet.",
        callout:{ label:"Where it wins", text:"If your work already flows through Google, Gemini reaches your real data, not a copy of it." },
        prompt:"Summarize the last 10 emails from this thread\nand draft a reply proposing Thursday at 2pm.",
        note:"Gemini's edge = your\nWorkspace data, in context." },
      { n:"02", title:"Gemini in Docs & Sheets", level:"Basics", dur:"5:00",
        desc:"Draft, rewrite, and analyze without leaving the file you're working in.",
        callout:{ label:"Help me write", text:"Use the side panel to draft and the @-menu to pull in other files as context." },
        prompt:"(In Sheets) \"Add a column that flags rows\nwhere spend grew >20% month over month,\nthen chart the top 5.\"",
        note:"It edits the real file,\nnot a pasted copy." },
      { n:"03", title:"Deep Research mode", level:"Practical", dur:"6:15",
        desc:"Send Gemini to browse, gather, and compile a cited research brief for you.",
        callout:{ label:"Let it browse", text:"Deep Research plans a search, reads dozens of pages, and returns an organized, sourced report." },
        prompt:"Research the EV charging market in Europe.\nGive me a brief with sources, key players,\nand 3 trends to watch.",
        note:"Deep Research = a junior\nanalyst that cites sources." },
      { n:"04", title:"Multimodal: image, audio, video", level:"Practical", dur:"5:35",
        desc:"Feed Gemini a screenshot, a recording, or a clip and ask questions about it.",
        callout:{ label:"Throw anything at it", text:"Gemini handles image, audio, and video natively — great for summarizing recordings." },
        prompt:"(Upload a 20-min meeting recording)\n\"Give me decisions made, action items\nwith owners, and open questions.\"",
        note:"Recording → action items\nin under a minute." },
      { n:"05", title:"Gems: your custom assistants", level:"Pro", dur:"5:10",
        desc:"Build reusable 'Gems' tuned to a role — like Custom GPTs, the Google way.",
        callout:{ label:"Make a Gem", text:"Define a role + instructions once and reuse it across all your Gemini chats." },
        prompt:"Create a Gem: \"Meeting Prep\".\nGiven a calendar invite, pull attendee context\nand draft 3 talking points.",
        note:"Gems = saved roles you\nreach for every day." },
      { n:"06", title:"When to use something else", level:"Pro", dur:"4:20",
        desc:"Gemini's tradeoffs and the tasks better handled by Claude or ChatGPT.",
        callout:{ label:"Honest tradeoffs", text:"Strong in the Google ecosystem; for deep reasoning or coding, compare against Claude." },
        prompt:"Compare your answer to how Claude\nmight handle this reasoning task.\nWhere might you differ?",
        note:"Best inside Google.\nCompare elsewhere for code." },
    ],
  },

  copilot: {
    name:"Copilot", by:"Microsoft", version:"Microsoft 365 · 2026", mark:"@copilot",
    tagline:"AI baked into Windows, Office, and Edge.",
    compare:[ {name:"ChatGPT"}, {name:"Gemini"}, {name:"Cursor"} ],
    lessons:[
      { n:"01", title:"What Copilot is (and isn't)", level:"Basics", dur:"3:15",
        desc:"How Copilot sits across Microsoft 365 — and how it differs from GitHub Copilot.",
        callout:{ label:"Two Copilots", text:"Microsoft 365 Copilot (Office) is different from GitHub Copilot (code). This page is the Office one." },
        prompt:"Summarize this Word doc into 5 bullets,\nthen draft an email to my team\nasking for feedback by Friday.",
        note:"Best if you live in\nOutlook, Word, Excel, Teams." },
      { n:"02", title:"Copilot in Word & Outlook", level:"Basics", dur:"4:55",
        desc:"Draft documents and triage your inbox without leaving the app.",
        callout:{ label:"Inbox triage", text:"Ask Copilot to summarize long threads and draft replies in your tone." },
        prompt:"(In Outlook) \"Summarize this 30-email thread,\nlist the decisions, and draft a reply\nconfirming next steps.\"",
        note:"Thread → decisions →\ndraft reply, in seconds." },
      { n:"03", title:"Excel analysis without formulas", level:"Practical", dur:"6:05",
        desc:"Ask questions of a spreadsheet in plain English and get formulas, charts, and pivots.",
        callout:{ label:"Plain-English Excel", text:"Describe what you want; Copilot writes the formula and explains it." },
        prompt:"(In Excel) \"Which region grew fastest\nlast quarter? Add a column showing\ngrowth % and a chart of the top 5.\"",
        note:"No VLOOKUP memorizing.\nJust ask." },
      { n:"04", title:"Teams meeting recap", level:"Practical", dur:"5:20",
        desc:"Let Copilot attend, transcribe, and summarize meetings with action items.",
        callout:{ label:"Never take notes again", text:"Copilot captures decisions and action items live, even if you join late." },
        prompt:"(In Teams) \"What did I miss in the\nfirst 15 minutes? List decisions\nand anything assigned to me.\"",
        note:"Join late, catch up\nin one prompt." },
      { n:"05", title:"PowerPoint from a document", level:"Pro", dur:"5:40",
        desc:"Turn a Word doc or prompt into a first-draft deck, then refine it.",
        callout:{ label:"Doc → deck", text:"Point Copilot at a document and it drafts a structured slide deck to edit." },
        prompt:"Create a 10-slide deck from this report.\nOne idea per slide, speaker notes,\nand a closing call-to-action.",
        note:"First-draft deck in a minute.\nYou polish from there." },
      { n:"06", title:"Security, data & limits", level:"Pro", dur:"4:30",
        desc:"How Copilot uses your org data, and where it falls short vs other models.",
        callout:{ label:"Stays in your tenant", text:"Enterprise Copilot respects your org's permissions — but check your admin's settings." },
        prompt:"Explain, in plain terms, what data\nCopilot can and can't see\nin my organization.",
        note:"Great for Office. Compare\nelsewhere for deep reasoning." },
    ],
  },

  cursor: {
    name:"Cursor", by:"Anysphere", version:"Cursor · 2026", mark:"@cursor",
    tagline:"The AI-native code editor pros are switching to.",
    compare:[ {name:"Claude"}, {name:"ChatGPT"}, {name:"DeepSeek"} ],
    lessons:[
      { n:"01", title:"Why an AI editor at all", level:"Basics", dur:"3:50",
        desc:"Cursor is a fork of VS Code with frontier models wired into every action.",
        callout:{ label:"It knows your repo", text:"Unlike a chat window, Cursor sees your whole codebase and edits files directly." },
        prompt:"(Cmd-K) \"Add input validation to this\nfunction and write a test for it.\"",
        note:"Chat doesn't see your repo.\nCursor does." },
      { n:"02", title:"Cmd-K: edit at the cursor", level:"Basics", dur:"4:25",
        desc:"Inline edits — describe a change and Cursor rewrites the selected code.",
        callout:{ label:"Inline magic", text:"Select code, hit Cmd-K, describe the change. Review the diff before accepting." },
        prompt:"(Select a function, Cmd-K)\n\"Make this async and handle errors\nwith a try/catch that logs context.\"",
        note:"Always read the diff\nbefore you accept." },
      { n:"03", title:"Chat with your codebase", level:"Basics", dur:"5:00",
        desc:"Ask questions about how your project works using @-references to files and symbols.",
        callout:{ label:"@ your files", text:"Use @file and @symbol so Cursor answers with your actual code, not a guess." },
        prompt:"@auth.ts @routes.ts\n\"Where is the login token validated,\nand what happens if it's expired?\"",
        note:"@-reference real files\nfor grounded answers." },
      { n:"04", title:"Agent mode: multi-file tasks", level:"Practical", dur:"7:10",
        desc:"Hand Cursor a goal and let it plan, edit multiple files, and run commands.",
        callout:{ label:"Delegate a task", text:"Agent mode breaks a goal into steps, edits across files, and shows you everything to approve." },
        prompt:"\"Add a dark mode toggle:\nstate, a button in the navbar,\nand persist the choice to localStorage.\"",
        note:"Agent = the intern.\nYou're still the reviewer." },
      { n:"05", title:"Picking the right model", level:"Practical", dur:"4:40",
        desc:"Cursor lets you swap the underlying model — when to use which.",
        callout:{ label:"Swap models", text:"Heavy reasoning? Use a frontier model. Quick edits? A faster, cheaper one is fine." },
        prompt:"Explain the tradeoff between using\na big model vs a fast model\nfor routine refactors.",
        note:"Big model to plan,\nfast model to grind." },
      { n:"06", title:"Guardrails & good habits", level:"Pro", dur:"5:15",
        desc:"Keeping AI edits safe: small diffs, tests, and version control discipline.",
        callout:{ label:"Stay in control", text:"Commit before big agent runs. Keep diffs small. Let tests be your safety net." },
        prompt:"Write tests that would catch a\nregression in this function before\nI let the agent refactor it.",
        note:"Commit first. Small diffs.\nTests catch the rest." },
    ],
  },

  midjourney: {
    name:"Midjourney", by:"Midjourney", version:"v8 · 2026", mark:"@midjourney",
    tagline:"The image AI that defined the aesthetic.",
    compare:[ {name:"ChatGPT"}, {name:"Claude"}, {name:"Gemini"} ],
    lessons:[
      { n:"01", title:"How Midjourney works", level:"Basics", dur:"3:35",
        desc:"Text-to-image basics, the web app, and why creatives reach for it first.",
        callout:{ label:"Start simple", text:"Describe a subject, a style, and a mood. Add detail only once you see the first results." },
        prompt:"a quiet violet-lit study room,\nfilm photography, soft window light,\nshallow depth of field",
        note:"Subject + style + light.\nThat's 80% of a good prompt." },
      { n:"02", title:"Prompt structure that works", level:"Basics", dur:"5:10",
        desc:"Subject, style, lighting, composition — and the parameters that control them.",
        callout:{ label:"Aspect ratio matters", text:"End your prompt with --ar 16:9 (or 1:1, 9:16). Never let it default to square by accident." },
        prompt:"minimalist product shot of a violet orb,\nstudio lighting, seamless backdrop,\nhigh detail --ar 1:1",
        note:"--ar sets shape.\n--stylize sets how 'arty'." },
      { n:"03", title:"Reference images & style", level:"Practical", dur:"6:00",
        desc:"Use image prompts and style references to lock a consistent look.",
        callout:{ label:"Lock the look", text:"Drop in a reference image to guide style or composition across a whole set." },
        prompt:"(Add a reference image)\n\"same color palette and mood,\nbut a city skyline at dusk\" --ar 16:9",
        note:"Reference image = consistent\nbrand look across shots." },
      { n:"04", title:"Iterating: vary & upscale", level:"Practical", dur:"5:25",
        desc:"Use variations, remix, and upscaling to refine a promising result.",
        callout:{ label:"Don't re-roll blindly", text:"Found something close? Use Vary (Subtle) and Remix instead of starting over." },
        prompt:"(On a result) Remix:\n\"keep everything, change the season\nto winter with soft snow\"",
        note:"Vary > re-roll once\nyou're close." },
      { n:"05", title:"Where it fits in a workflow", level:"Pro", dur:"5:00",
        desc:"Pairing Midjourney with ChatGPT for prompt ideas and Claude for art direction.",
        callout:{ label:"Chain it", text:"Brainstorm prompts in ChatGPT, generate in Midjourney, critique with Claude. Repeat." },
        prompt:"(In ChatGPT) \"Give me 5 Midjourney prompts\nfor a calm, premium fintech brand,\nviolet palette.\"",
        note:"ChatGPT writes prompts,\nMidjourney renders them." },
      { n:"06", title:"Limits & licensing", level:"Pro", dur:"4:15",
        desc:"What Midjourney can't do, plus the basics of usage rights for your images.",
        callout:{ label:"Know the rules", text:"Check your plan's commercial terms before using generations in client work." },
        prompt:"List what Midjourney struggles with\n(text in images, precise layouts)\nand what to use instead.",
        note:"Great for mood. Weak on\nexact text & UI layouts." },
    ],
  },

  perplexity: {
    name:"Perplexity", by:"Perplexity", version:"2026", mark:"@perplexity",
    tagline:"AI search with live results and citations.",
    compare:[ {name:"ChatGPT"}, {name:"Claude"}, {name:"Grok"} ],
    lessons:[
      { n:"01", title:"Search, not just chat", level:"Basics", dur:"3:25",
        desc:"Why Perplexity is built for research: live web results with sources you can check.",
        callout:{ label:"Always cited", text:"Every answer comes with links. When facts matter, that's the whole point." },
        prompt:"What changed in the latest EU AI Act draft?\nCite primary sources and quote the key clause.",
        note:"Facts with citations.\nVerify before you trust." },
      { n:"02", title:"Focus modes & sources", level:"Basics", dur:"4:30",
        desc:"Narrow searches to academic, social, or specific domains for better answers.",
        callout:{ label:"Aim the search", text:"Use Focus to restrict to Academic or a specific site when you need authority." },
        prompt:"(Academic focus) \"Find peer-reviewed\nstudies on spaced repetition\nfrom the last 5 years.\"",
        note:"Focus mode = better\nsources, less noise." },
      { n:"03", title:"Follow-ups & threads", level:"Basics", dur:"4:05",
        desc:"Drill into a topic with follow-up questions that keep the sources in context.",
        callout:{ label:"Keep pulling", text:"Each follow-up stays grounded in the same sources, so you can dig without losing the thread." },
        prompt:"\"Now compare those two approaches\nin a table, with the source\nfor each claim.\"",
        note:"Drill down — sources\ncarry through the thread." },
      { n:"04", title:"Spaces for ongoing research", level:"Practical", dur:"5:30",
        desc:"Organize a long research project with saved sources and shared context.",
        callout:{ label:"Project memory", text:"A Space keeps your sources and questions together for a multi-day research effort." },
        prompt:"Create a Space for \"market entry: Japan\".\nStart with regulations, competitors,\nand distribution channels.",
        note:"Spaces = a research\nbinder that thinks." },
      { n:"05", title:"From research to draft", level:"Practical", dur:"5:15",
        desc:"The classic hand-off: gather facts in Perplexity, write in Claude or ChatGPT.",
        callout:{ label:"The hand-off", text:"Perplexity finds and verifies; paste the cited findings into Claude to synthesize and write." },
        prompt:"Summarize my Space into a sourced\noutline I can hand to Claude\nto turn into a report.",
        note:"Perplexity = facts.\nClaude = the writing." },
      { n:"06", title:"Trust, but verify", level:"Pro", dur:"4:00",
        desc:"How to read citations critically and catch when a source is weak.",
        callout:{ label:"Check the link", text:"Citations make it easy — actually click them. A confident answer with a weak source is still weak." },
        prompt:"For each claim in your last answer,\nrate the source quality 1-5\nand flag anything shaky.",
        note:"Cited ≠ correct.\nClick the sources." },
    ],
  },

  llama: {
    name:"Llama", by:"Meta", version:"Llama 4 · 2026", mark:"@llama",
    tagline:"The open-weight model you can run yourself.",
    compare:[ {name:"DeepSeek"}, {name:"ChatGPT"}, {name:"Claude"} ],
    lessons:[
      { n:"01", title:"What 'open weights' means", level:"Basics", dur:"3:40",
        desc:"Why a downloadable model changes the game for privacy, cost, and control.",
        callout:{ label:"You hold the model", text:"Open weights mean you can run Llama on your own hardware — no data leaves your machine." },
        prompt:"Explain the difference between\nopen-weight and closed models\nfor someone non-technical.",
        note:"Open weights = privacy,\ncontrol, and no per-token bill." },
      { n:"02", title:"Running Llama locally", level:"Basics", dur:"5:20",
        desc:"The easiest ways to run Llama on a laptop with tools like Ollama.",
        callout:{ label:"One command", text:"Tools like Ollama make local Llama a single command. Quantized models run on a laptop." },
        prompt:"(In a terminal)\nollama run llama4\n\"Summarize this file offline.\"",
        note:"Quantized = smaller, faster,\nruns offline on a laptop." },
      { n:"03", title:"When local beats the cloud", level:"Basics", dur:"4:15",
        desc:"Privacy-sensitive data, offline use, and high-volume tasks where cost adds up.",
        callout:{ label:"Pick local when…", text:"Sensitive data, no internet, or huge volume where API costs would balloon." },
        prompt:"List 5 tasks where running a model\nlocally is clearly better than\nusing a cloud API.",
        note:"Local wins on privacy,\noffline, and volume." },
      { n:"04", title:"Fine-tuning on your data", level:"Practical", dur:"7:00",
        desc:"Teach Llama your domain, tone, or task with lightweight fine-tuning.",
        callout:{ label:"Make it yours", text:"Fine-tune on your docs so Llama speaks your domain — without sending data to a vendor." },
        prompt:"Outline the steps to fine-tune Llama\non our support tickets so it answers\nin our house style.",
        note:"Fine-tune = a model that\nknows your world." },
      { n:"05", title:"Building apps on Llama", level:"Practical", dur:"6:10",
        desc:"Using Llama as the engine behind your own tools and assistants.",
        callout:{ label:"Your own stack", text:"Pair Llama with a vector database for private retrieval-augmented apps you fully own." },
        prompt:"Sketch an architecture for a private\nQ&A bot over our internal wiki\nusing Llama + a vector store.",
        note:"Llama + your data =\nan app no vendor controls." },
      { n:"06", title:"Tradeoffs vs frontier models", level:"Pro", dur:"4:45",
        desc:"Where open models trail the best closed ones — and where that doesn't matter.",
        callout:{ label:"Be honest", text:"Frontier closed models still lead on the hardest reasoning. For most tasks, Llama is plenty." },
        prompt:"For my use case, does a local Llama\ngive up anything important vs\na frontier API? Be specific.",
        note:"Good enough, private, free.\nOften that's the win." },
    ],
  },

  deepseek: {
    name:"DeepSeek", by:"DeepSeek", version:"2026", mark:"@deepseek",
    tagline:"Frontier reasoning at a fraction of the cost.",
    compare:[ {name:"Llama"}, {name:"Cursor"}, {name:"Claude"} ],
    lessons:[
      { n:"01", title:"The cheap-reasoning breakthrough", level:"Basics", dur:"3:30",
        desc:"Why DeepSeek made headlines: strong reasoning without OpenAI-scale spending.",
        callout:{ label:"Why it matters", text:"DeepSeek showed frontier-ish reasoning is possible far cheaper — which reshapes who can compete." },
        prompt:"Explain why a cheaper frontier model\nmatters for startups and researchers,\nin plain terms.",
        note:"Cheap reasoning = more\npeople can build." },
      { n:"02", title:"Reasoning mode explained", level:"Basics", dur:"4:50",
        desc:"How DeepSeek 'thinks' step by step before answering, and when that helps.",
        callout:{ label:"Let it think", text:"For math, logic, and code, reasoning mode trades a few seconds for much better answers." },
        prompt:"Solve this logic puzzle.\nShow your reasoning step by step,\nthen give the final answer.",
        note:"Reasoning mode: slower,\nbut far smarter on hard tasks." },
      { n:"03", title:"Using DeepSeek for code", level:"Practical", dur:"5:40",
        desc:"Strong, low-cost code generation — and how to wire it into editors like Cursor.",
        callout:{ label:"Cheap code engine", text:"DeepSeek is a budget-friendly engine for routine coding; plug it into Cursor for repo context." },
        prompt:"Write a Python script that dedupes\na CSV by email, keeps the newest row,\nand logs what it removed.",
        note:"Great value for grind-y\ncoding tasks." },
      { n:"04", title:"Open weights & self-hosting", level:"Practical", dur:"5:30",
        desc:"DeepSeek's open releases let you run it yourself, like Llama.",
        callout:{ label:"Run it yourself", text:"Open weights mean you can self-host for privacy and skip per-token costs entirely." },
        prompt:"Compare self-hosting DeepSeek vs Llama\nfor a privacy-sensitive coding tool.\nWhat are the tradeoffs?",
        note:"Self-host for privacy +\nzero marginal cost." },
      { n:"05", title:"Cost-aware AI strategy", level:"Pro", dur:"5:00",
        desc:"Routing cheap tasks to DeepSeek and hard ones to a frontier model.",
        callout:{ label:"Route by difficulty", text:"Send routine calls to DeepSeek, escalate only the hardest prompts to a pricier model." },
        prompt:"Design a routing rule: which prompts\ngo to a cheap model vs a frontier one?\nGive concrete criteria.",
        note:"Cheap by default,\nescalate when it's hard." },
      { n:"06", title:"Limits & cautions", level:"Pro", dur:"4:10",
        desc:"Where DeepSeek trails, plus data and provenance considerations to weigh.",
        callout:{ label:"Do your diligence", text:"Evaluate on your own tasks and review your data-handling policy before production use." },
        prompt:"What should I test before trusting\nDeepSeek in production?\nGive me an evaluation checklist.",
        note:"Test on your tasks\nbefore you ship." },
    ],
  },

  grok: {
    name:"Grok", by:"xAI", version:"Grok 4 · 2026", mark:"@grok",
    tagline:"Real-time, social-native, deliberately unfiltered.",
    compare:[ {name:"Perplexity"}, {name:"ChatGPT"}, {name:"Claude"} ],
    lessons:[
      { n:"01", title:"What makes Grok different", level:"Basics", dur:"3:20",
        desc:"Grok's tight tie to X (Twitter) and its more casual, less-filtered tone.",
        callout:{ label:"The angle", text:"Grok leans into real-time social signal and a looser personality. Useful — and worth double-checking." },
        prompt:"What are people on X saying about\n{topic} in the last 24 hours?\nSummarize the main camps.",
        note:"Real-time social pulse.\nVerify the spicy claims." },
      { n:"02", title:"Real-time on X", level:"Basics", dur:"4:30",
        desc:"Using Grok to read the room on breaking topics and trends as they happen.",
        callout:{ label:"Live signal", text:"Grok's access to X makes it strong for 'what's happening right now' questions." },
        prompt:"Track reactions to today's product launch.\nWho's excited, who's critical,\nand what's the common complaint?",
        note:"Good for now.\nNot a source of record." },
      { n:"03", title:"Tone & 'fun mode'", level:"Basics", dur:"3:55",
        desc:"Grok's personality settings — when a looser voice helps and when it hurts.",
        callout:{ label:"Pick the voice", text:"A casual tone is great for brainstorming, less great for a board memo. Switch modes to fit." },
        prompt:"Give me a punchy, irreverent take on\n{topic}, then a serious,\nboardroom-ready version.",
        note:"Casual to brainstorm,\nserious to ship." },
      { n:"04", title:"Research with a skeptic's eye", level:"Practical", dur:"5:25",
        desc:"Pairing Grok's live signal with Perplexity's citations to separate noise from fact.",
        callout:{ label:"Two-step it", text:"Get the vibe from Grok, then verify the actual claims in Perplexity with sources." },
        prompt:"List the top 3 claims trending about\n{topic}, then tell me which\nto fact-check first.",
        note:"Grok for signal,\nPerplexity to verify." },
      { n:"05", title:"Vision & everyday tasks", level:"Practical", dur:"5:00",
        desc:"Grok beyond the timeline: images, drafting, and general assistant work.",
        callout:{ label:"More than X", text:"Grok handles images and general tasks too — try it as a day-to-day assistant." },
        prompt:"(Upload a photo)\n\"Draft a witty caption and 3\nalternate tones for this.\"",
        note:"Capable generalist,\nwith a sharper tongue." },
      { n:"06", title:"Bias, limits & judgment", level:"Pro", dur:"4:35",
        desc:"Reading Grok critically: its tone is a feature and a risk. Keep your guard up.",
        callout:{ label:"Stay critical", text:"A confident, edgy answer can still be wrong. Use Grok's speed, keep your own judgment." },
        prompt:"Where might your tone bias an answer\non a controversial topic?\nGive me the straight version.",
        note:"Personality is a feature —\nand a thing to watch." },
    ],
  },
};

Object.assign(window, { MODELS_CATALOG });

const LOGO_SRC = { "@chatgpt": "logos/chatgpt.png", "@claude": "logos/claude.svg", "@gemini": "logos/gemini.webp", "@copilot": "logos/copilot.png", "@cursor": "logos/cursor.png", "@midjourney": "logos/midjourney.png", "@perplexity": "logos/perplexity.png", "@llama": "logos/llama.png", "@deepseek": "logos/deepseek.png", "@grok": "logos/grok.webp" };
window.LOGO_SRC = LOGO_SRC;
function MarkGlyph({ mark }) {
  if (LOGO_SRC[mark]) {
    return <img src={LOGO_SRC[mark]} alt="" style={{ width:"70%", height:"70%", objectFit:"contain", display:"block" }} />;
  }
  return mark;
}
window.MarkGlyph = MarkGlyph;
